#!/bin/sh

# Format js and html by prettier
files=$(git diff --cached --name-only --diff-filter=AMCR -- '*.html' '*.css' '*.js' '*.vue' '*.jsx')
if [[ -n $files ]];
then
    docker-compose run --rm npx prettier --ignore-unknown --write $files --config .prettierrc 2>/dev/null
    git add $files
else
	echo "There is no *.html, *.css, *.js, *.vue, *jsx files to format."
fi


# Format php by laravel pint
files=$(git diff --cached --name-only --diff-filter=AMCR -- '*.php')
if [[ -n $files ]];
then
    docker-compose run --rm pint --config pint.json $files 2>/dev/null
    git add $files
else
	echo "There is no *.php files to format."
fi

# Format blade by blade formatter
files=$(git diff --cached --name-only --diff-filter=AMCR  -- '*.blade.php')
if [[ -n $files ]];
then
    docker-compose run --rm npx blade-formatter --write $files --config .bladeformatterrc.json 2>/dev/null
    git add $files
else
	echo "There is no *.blade.php files to format."
fi

# Handle errors if necessary
if [ $? -ne 0 ]; then
    echo "Error: Docker Compose command failed. Please fix the issue before committing."
    exit 1
fi