version: '3.8'

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - laravel
        depends_on:
            - php

    php:
        container_name: php
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        depends_on:
            - mysql

    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: always
        tty: true
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
            # MYSQL_USER: '${DB_USERNAME}'
            # MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            # MYSQL_ALLOW_EMPTY_PASSWORD: yes
        networks:
            - laravel

    composer:
        container_name: composer
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        entrypoint: ['composer']
        networks:
            - laravel

    artisan:
        container_name: artisan
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        entrypoint: ['php','artisan']
        networks:
            - laravel

    pint:
        container_name: pint
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        entrypoint: ['php','vendor/bin/pint']
        networks:
            - laravel

    npm:
        container_name: npm
        image: node:current-alpine
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    npx:
        container_name: prettier
        image: node:current-alpine
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        working_dir: /var/www/html
        entrypoint: ['npx']
        networks:
            - laravel

    # redis:
    #     container_name: redis
    #     image: redis:alpine
    #     restart: unless-stopped
    #     volumes:
    #         - "./.docker/redis:/data"
    #     ports:
    #         - '${REDIS_PORT:-6379}:6379'
    #     networks:
    #         - laravel

    mail:
        container_name: mail
        image: rnwood/smtp4dev:linux-amd64-v3
        ports:
            - 1000:80
        networks:
            - laravel

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql
        networks:
            - laravel